### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by blackary** [sebastiandres/streamlit_happy_birds#1]
TypeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
```
File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/scriptrunner/script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
File "/app/streamlit_happy_birds/happy_birds.py", line 8, in <module>
    stb.set_book_config(path="HappyBirds")
```

**Comment by sebastiandres** [comment]
Thanks! Corrected and working!

The newest version is backwards incompatible and caused an error. It required a simple fix on the requirements:
streamlit-book==0.5.2
